# Generated by Django 5.0.2 on 2026-08-14 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0029_device_final_audit_device_initial_audit'),
        ('donations', '0004_donationpledge_donor_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ORDER', 'Fulfilment request'), ('DONATION', 'Donation pledge')], max_length=10)),
                ('prepared_for', models.CharField(max_length=200)),
                ('device_count', models.PositiveIntegerField()),
                ('excluded_count', models.PositiveIntegerField(default=0)),
                ('total_gwp_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakdown_json', models.JSONField(default=dict)),
                ('constants_json', models.JSONField(default=dict)),
                ('methodology_version', models.CharField(max_length=40)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='environmental_reports/')),
                ('donation_pledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_reports', to='donations.donationpledge')),
                ('fulfilment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_reports', to='devices.fulfilmentrequest')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
