# Generated by Django 5.0.2 on 2026-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound — Workbench → ERPNext'), ('INBOUND', 'Inbound — ERPNext → Workbench (webhook)')], max_length=10)),
                ('doctype', models.CharField(blank=True, help_text='ERPNext DocType (e.g. Sales Order)', max_length=100)),
                ('doc_name', models.CharField(blank=True, help_text='ERPNext document name/ID', max_length=100)),
                ('action', models.CharField(help_text='e.g. create, update, get, sync_customers', max_length=50)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
