# Generated by Django 5.0.2 on 2026-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_cachedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedarAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('refreshed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Cedar Auth Token',
                'verbose_name_plural': 'Cedar Auth Token',
            },
        ),
    ]
