# Generated by Django 5.0.2 on 2026-05-20 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0005_alter_devicespecification_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWipeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('NOT_REQUIRED', 'Not Required')], default='SUCCESS', max_length=20)),
                ('wipe_method', models.CharField(blank=True, max_length=100)),
                ('wipe_standard', models.CharField(default='NIST 800-88', max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='wipe_certificates/')),
                ('wiped_by', models.CharField(blank=True, max_length=100)),
                ('wiped_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipe_records', to='devices.device')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
