# Generated by Django 5.0.2 on 2026-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datawiperecord',
            name='certificate_type',
            field=models.CharField(choices=[('ERASE', 'Erase Certificate'), ('AUDIT', 'Audit Certificate')], default='ERASE', help_text='Whether this is an erase or audit certificate from Cedar', max_length=10),
        ),
        migrations.AddField(
            model_name='datawiperecord',
            name='json_data',
            field=models.JSONField(blank=True, help_text='Raw JSON from Cedar certificate', null=True),
        ),
        migrations.AlterField(
            model_name='datawiperecord',
            name='result',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('NOT_REQUIRED', 'Not Required')], default='SUCCESS', max_length=20),
        ),
    ]
