# Generated by Django 5.0.2 on 2026-08-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_devicespecification_hdmodel_raw_and_more'),
        ('wipe', '0002_datawiperecord_certificate_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('NOT_TESTED', 'Not Tested'), ('NOT_APPLICABLE', 'Not Applicable')], default='PASS', max_length=20)),
                ('test_results', models.JSONField(blank=True, help_text='Full Cedar asset certificate JSON', null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='audit_certificates/')),
                ('auditor', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
