# Generated by Django 5.0.2 on 2026-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wipe', '0003_auditrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='cedar_certificate_id',
            field=models.CharField(blank=True, db_index=True, help_text="Cedar's internal certificate ID (idempotency key)", max_length=100, null=True),
        ),
    ]
