# Generated by Django 5.0.2 on 2026-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('code', models.CharField(help_text='Stage code (e.g., RECEIVED, DATA_WIPE)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('sequence', models.IntegerField(help_text='Order in workflow')),
                ('is_terminal', models.BooleanField(default=False, help_text='True if no further transitions allowed')),
                ('quality_gate_checklist', models.JSONField(blank=True, default=dict, help_text='Required checks before exit')),
                ('required_photo_types', models.JSONField(blank=True, default=list, help_text='Photo types required before exit')),
                ('allowed_next_stages', models.ManyToManyField(blank=True, help_text='Valid transitions from this stage', to='workflow.stage')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
