# Generated by Django 5.0.2 on 2026-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_add_stage_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='default_zone',
            field=models.CharField(blank=True, help_text='Expected racking zone (e.g., A, B, C)', max_length=10),
        ),
    ]
