"""Data Erasure Summary sheet for a donation pledge.

Renders a branded one-page PDF summarising the wipe status of every
device in a donation pledge. Generated on-demand from the database
(no Cedar API call).
"""
from datetime import datetime
from pathlib import Path

from django.http import HttpResponse
from django.template import Context, Engine
from weasyprint import HTML

from devices.models import Device
from wipe.models import DataWipeRecord

LOGO_PATH = Path("/app/core/static/core/Logo.svg")

RESULT_LABELS = {
    "SUCCESS": "Passed",
    "PASS": "Passed",
    "FAILED": "Failed",
    "FAIL": "Failed",
    "NOT_REQUIRED": "Not Required",
}

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Data Erasure Summary</title>
  <style>
    @page { size: A4; margin: 2cm; }
    body { font-family: "Helvetica Neue", Arial, sans-serif; color: #222; font-size: 10pt; }
    .logo { height: 60px; display: block; margin: 0 auto 10pt auto; }
    h1 { font-size: 20pt; text-align: center; margin: 0 0 2pt 0; }
    .subtitle { text-align: center; color: #555; margin: 0 0 16pt 0; font-size: 11pt; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 12pt; }
    th, td { border: 1px solid #bbb; padding: 5pt 6pt; text-align: left; vertical-align: top; font-size: 9pt; }
    th { background: #f0f0f0; font-weight: 600; }
    .pass { color: #0a7a0a; font-weight: 600; }
    .fail { color: #b00000; font-weight: 600; }
    .pending { color: #b07000; font-weight: 600; }
    .meta td { border: none; padding: 2pt 4pt; font-size: 10pt; }
    .footer { margin-top: 20pt; font-size: 8.5pt; color: #555; text-align: center; }
  </style>
</head>
<body>
  {% if logo_url %}<img src="{{ logo_url }}" class="logo" alt="ReCognition Circular">{% endif %}
  <h1>Data Erasure Summary</h1>
  <p class="subtitle">{{ pledge.reference_number }} &mdash; {{ pledge.donor_name }}</p>

  <table class="meta">
    <tr>
      <td><strong>Donor:</strong> {{ pledge.donor_name }}</td>
      <td><strong>Pledge reference:</strong> {{ pledge.reference_number }}</td>
      <td><strong>Devices:</strong> {{ rows|length }}</td>
    </tr>
    <tr>
      <td><strong>Generated:</strong> {{ generated_at }}</td>
      <td colspan="2"><strong>Organisation:</strong> ReCognition Circular CIC</td>
    </tr>
  </table>

  <table>
    <thead>
      <tr>
        <th>Device Serial</th>
        <th>Make / Model</th>
        <th>Inventory #</th>
        <th>Drive Serial(s)</th>
        <th>Result</th>
        <th>Standard</th>
        <th>Wipe Date</th>
      </tr>
    </thead>
    <tbody>
      {% for row in rows %}
      <tr>
        <td>{{ row.serial }}</td>
        <td>{{ row.make_model }}</td>
        <td>{{ row.inventory }}</td>
        <td>{{ row.drive_serials }}</td>
        <td class="{{ row.css }}">{{ row.result }}</td>
        <td>{{ row.standard }}</td>
        <td>{{ row.wipe_date }}</td>
      </tr>
      {% empty %}
      <tr><td colspan="7">No devices found for this pledge.</td></tr>
      {% endfor %}
    </tbody>
  </table>

  <p class="footer">
    Drive serial numbers identify the storage media erased for each device.
    Devices shown as &ldquo;Pending&rdquo; have not yet returned an erasure record.
    Generated by the ReCognition Circular Workbench.
  </p>
</body>
</html>
"""


def _logo_url():
    return LOGO_PATH.as_uri() if LOGO_PATH.exists() else ""


def _make_model(spec):
    if not spec:
        return "&mdash;"
    parts = [p for p in (spec.manufacturer, spec.model_name, spec.model_number) if p]
    return " ".join(parts) if parts else "&mdash;"


def _drive_serials(record, spec):
    serials = []
    items = (record.json_data or {}).get("erasure_results", []) if record else []
    for item in items:
        if isinstance(item, dict) and item.get("serial_number"):
            serials.append(str(item["serial_number"]))
    if serials:
        return ", ".join(serials)
    if spec and spec.drive_serial:
        return spec.drive_serial
    return "&mdash;"


def _result_parts(device, record):
    """Return (label, css_class)."""
    if record:
        raw = record.result or ""
        if raw in ("PASS", "SUCCESS"):
            return RESULT_LABELS.get(raw, raw), "pass"
        if raw in ("FAIL", "FAILED"):
            return RESULT_LABELS.get(raw, raw), "fail"
        if raw == "NOT_REQUIRED":
            return "Not Required", "pending"
        return raw or "&mdash;", "pending"
    if device.wipe_status in ("PASS", "DONOR_WIPED"):
        return "Passed", "pass"
    if device.wipe_status == "FAIL":
        return "Failed", "fail"
    return "Pending", "pending"


def build_rows(pledge):
    devices = (
        Device.objects.filter(donation_pledge=pledge)
        .select_related("device_specification")
        .order_by("inventory_number")
    )
    erase_by_device = {
        r.device_id: r
        for r in DataWipeRecord.objects.filter(
            device__donation_pledge=pledge, certificate_type="ERASE"
        )
    }

    rows = []
    for d in devices:
        spec = d.device_specification
        record = erase_by_device.get(d.id)
        result, css = _result_parts(d, record)

        rows.append({
            "serial": d.serial_number or "&mdash;",
            "make_model": _make_model(spec),
            "inventory": d.inventory_number or "&mdash;",
            "drive_serials": _drive_serials(record, spec),
            "result": result,
            "css": css,
            "standard": (record.wipe_standard if record and record.wipe_standard else "&mdash;"),
            "wipe_date": record.wiped_at.strftime("%d %b %Y") if record and record.wiped_at else "&mdash;",
        })
    return rows


def render_summary_pdf(pledge):
    rows = build_rows(pledge)
    context = {
        "logo_url": _logo_url(),
        "pledge": pledge,
        "rows": rows,
        "generated_at": datetime.now().strftime("%d %B %Y %H:%M"),
    }
    engine = Engine()
    template = engine.from_string(TEMPLATE)
    html_string = template.render(Context(context))
    return HTML(string=html_string, base_url=str(LOGO_PATH.parent)).write_pdf()


def donor_erasure_summary(request):
    from donations.models import DonationPledge

    reference = request.GET.get("reference", "").strip()
    if not reference:
        return HttpResponse("Missing pledge reference.", status=400)

    try:
        pledge = DonationPledge.objects.get(reference_number=reference)
    except DonationPledge.DoesNotExist:
        return HttpResponse("Pledge reference not found.", status=404)

    pdf_bytes = render_summary_pdf(pledge)
    response = HttpResponse(pdf_bytes, content_type="application/pdf")
    response["Content-Disposition"] = (
        f"inline; filename=\"{pledge.reference_number}_data_erasure_summary.pdf\""
    )
    return response
