# Generated by Django 5.0.2 on 2026-08-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('devices', '0026_alter_device_allocation_intent_repairtask'),
        ('workflow', '0006_add_qa_remove_dispatched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Slug: check-in, refurb, qa', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklists', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instances', to='devices.device')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_instances', to='workflow.stage')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_checklists', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='checklists.checklisttemplate')),
            ],
            options={
                'unique_together': {('device', 'template')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(help_text='Display sequence within the template')),
                ('section_label', models.CharField(help_text="Grouping header, e.g. 'Physical Track', 'BIOS'", max_length=100)),
                ('label', models.CharField(help_text='Text shown to the technician', max_length=255)),
                ('item_type', models.CharField(choices=[('PASS_FAIL', 'Pass / Fail'), ('YES_NO', 'Yes / No'), ('DONE_NOT_DONE', 'Done / Not Done'), ('SELECT', 'Select (dropdown)'), ('TEXT', 'Text')], default='PASS_FAIL', max_length=20)),
                ('options', models.JSONField(blank=True, help_text="Options for SELECT type, e.g. ['Win 11','Ubuntu']", null=True)),
                ('is_auto_populated', models.BooleanField(default=False, help_text='Filled by system, not technician')),
                ('auto_source', models.CharField(blank=True, choices=[('CEDAR_TEST', 'Cedar diagnostic test'), ('DEVICE_SPEC', 'Device specification'), ('DATAWIPE_RECORD', 'Data-wipe record'), ('REFURB_STATUS', 'Refurb status')], help_text='Where the auto-value comes from', max_length=50, null=True)),
                ('cedar_component_key', models.CharField(blank=True, help_text="Key in Cedar test_results JSON, e.g. 'Motherboard'", max_length=100, null=True)),
                ('weight_tier', models.IntegerField(blank=True, choices=[(0, 'Tier 0 — Critical (10 pts)'), (1, 'Tier 1 — Major (5 pts)'), (2, 'Tier 2 — Moderate (3 pts)'), (3, 'Tier 3 — Low (1 pt)')], help_text='Tier used in auto-grade calculation for Cedar failures', null=True)),
                ('photo_required', models.BooleanField(default=False)),
                ('max_photos', models.IntegerField(default=0, help_text='Max photos for this item (0-3 for defects)')),
                ('generates_defect', models.BooleanField(default=False, help_text='Auto-create Defect record on FAIL response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'ordering': ['template', 'order_number'],
                'unique_together': {('template', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, help_text='Boolean, string, or null', null=True)),
                ('notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checklistinstance')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklisttemplateitem')),
            ],
            options={
                'unique_together': {('instance', 'template_item')},
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('CHECKIN_PHYSICAL', 'Check-in — Physical Track'), ('CEDAR_TEST', 'Check-in — Cedar Test')], max_length=20)),
                ('generates_refurb_item', models.BooleanField(default=True, help_text='Auto-include in Refurb checklist Section 4')),
                ('resolution_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('FIXED', 'Fixed'), ('WONT_FIX', "Won't Fix"), ('DEFERRED', 'Deferred')], default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_response', models.ForeignKey(blank=True, help_text='Response at check-in stage that triggered this defect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_defects', to='checklists.checklistitemresponse')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='devices.device')),
                ('repair_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_defects', to='devices.repairtask')),
                ('resolution_response', models.ForeignKey(blank=True, help_text='Response at refurb stage that resolved this defect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to='checklists.checklistitemresponse')),
                ('source_item', models.ForeignKey(blank=True, help_text='Which template item generated this defect', null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklisttemplateitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After'), ('EXIT_TOP', 'Exit — Top Cover'), ('EXIT_BOTTOM', 'Exit — Bottom'), ('EXIT_SCREEN', 'Exit — Screen'), ('EXIT_KEYBOARD', 'Exit — Keyboard'), ('BOOT', 'Boot'), ('DAMAGE_DETAIL', 'Damage Detail')], max_length=20)),
                ('image', models.ImageField(upload_to='device_photos/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='devices.device')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
