# Generated by Django 5.0.2 on 2026-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text="Reason for Won't Fix or Deferred resolution"),
        ),
    ]
