# Generated by Django 5.0.2 on 2026-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_add_resolution_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='defect_trigger_value',
            field=models.CharField(blank=True, choices=[('FAIL', 'Fail'), ('YES', 'Yes'), ('NO', 'No')], help_text='Response value that creates a Defect. Blank = never creates a defect.', max_length=10, null=True),
        ),
    ]
