# Generated by Django 5.0.2 on 2026-08-19 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_update_refurb_spec_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistitemresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistitemresponse',
            name='defect',
            field=models.ForeignKey(blank=True, help_text='Resolution response for a defect (template_item is null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.defect'),
        ),
        migrations.AlterField(
            model_name='checklistitemresponse',
            name='template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklisttemplateitem'),
        ),
        migrations.AddConstraint(
            model_name='checklistitemresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('template_item__isnull', False)), fields=('instance', 'template_item'), name='unique_response_template_item'),
        ),
        migrations.AddConstraint(
            model_name='checklistitemresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('defect__isnull', False)), fields=('instance', 'defect'), name='unique_response_defect'),
        ),
    ]
