# Generated by Django 5.0.2 on 2026-05-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('code', models.CharField(help_text='Site code (e.g., RECOGNITION_DIGBETH)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Site name (e.g., ReCognition - Digbeth)', max_length=200)),
                ('address', models.TextField(help_text='Full postal address')),
                ('is_active', models.BooleanField(default=True, help_text='Currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When site was added')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When site was closed if applicable', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('code', models.CharField(help_text='Location code (e.g., A1-1 or B2-3)', max_length=20, primary_key=True, serialize=False)),
                ('zone', models.CharField(help_text='Top level such as A, B, C', max_length=10)),
                ('shelf', models.CharField(help_text='Second level such as 1, 2, 3, 4', max_length=10)),
                ('section', models.CharField(help_text='Third level such as 1, 2, 3', max_length=10)),
                ('description', models.CharField(blank=True, help_text='Human-readable name (optional)', max_length=200)),
                ('barcode', models.CharField(help_text='Location barcode (unique)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When location was added')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When decommissioned if applicable', null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='For hierarchy (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.location')),
                ('site', models.ForeignKey(help_text='Which premises', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.site')),
            ],
            options={
                'ordering': ['zone', 'shelf', 'section'],
            },
        ),
    ]
