# Generated by Django 5.0.2 on 2026-05-09 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Optional note about the move')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the scan occurred')),
                ('device', models.ForeignKey(help_text='The device that was scanned', on_delete=django.db.models.deletion.CASCADE, related_name='location_scans', to='devices.device')),
                ('from_location', models.ForeignKey(blank=True, help_text='Previous location (null if first scan)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_from', to='locations.location')),
                ('scanned_by', models.ForeignKey(blank=True, help_text='Staff member who performed the scan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(help_text='New location after scan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_to', to='locations.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
