# Generated by Django 5.0.2 on 2026-05-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_add_location_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='max_size',
            field=models.CharField(choices=[('SMALL', 'Small (Laptop)'), ('MEDIUM', 'Medium (Desktop)'), ('LARGE', 'Large (AIO/Server)')], default='SMALL', help_text='Maximum device size this location can hold', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Free text notes about this location'),
        ),
        migrations.AddField(
            model_name='location',
            name='purpose',
            field=models.CharField(choices=[('DEVICE', 'Device Storage'), ('SUPPLIES', 'Supplies'), ('TOOLS', 'Tools'), ('RECYCLING', 'Recycling'), ('MIXED', 'Mixed')], default='DEVICE', help_text='What this location is used for', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='Location barcode (unique, leave blank to use code)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(help_text='Location code (e.g., MH18D04 or A1-1)', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Third level such as 1, 2, 3', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='shelf',
            field=models.CharField(blank=True, default='', help_text='Second level such as 1, 2, 3, 4', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='zone',
            field=models.CharField(help_text='Physical zone e.g., CHECK IN, WIP, FINISHED STOCK, MISC', max_length=20),
        ),
    ]
