# Generated by Django 5.0.2 on 2026-07-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_max_size_location_notes_location_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='triggers_stage',
            field=models.CharField(blank=True, help_text="If set, scanning a device to this location will attempt this stage transition (must match a Stage.code value, e.g. 'GRADING', 'IN_REFURB', 'QA_PENDING')", max_length=30, null=True),
        ),
    ]
