# Generated by Django 5.0.2 on 2026-05-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('locations', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('processor', models.CharField(blank=True, max_length=200)),
                ('memory_gb', models.IntegerField(blank=True, null=True)),
                ('storage_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVME', 'NVMe'), ('EMMC', 'eMMC'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('storage_size_gb', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('FOG', 'FOG auto-detected'), ('CEDAR', 'Cedar audit'), ('MANUAL', 'Entered manually')], default='FOG', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('ALL_IN_ONE', 'All-in-One'), ('TABLET', 'Tablet'), ('SERVER', 'Server'), ('OTHER', 'Other')], default='LAPTOP', max_length=20)),
                ('ownership_type', models.CharField(choices=[('DONATION', 'Ownership transfers to ReCognition'), ('RAAS', 'Refurb-as-a-Service (ownership stays with donor)'), ('LEASE_ASSET', 'ReCognition-owned asset for leasing'), ('INTERNAL', 'Internal use device')], default='DONATION', max_length=20)),
                ('grade', models.CharField(choices=[('A', 'Grade A - Excellent'), ('B', 'Grade B - Good'), ('C', 'Grade C - Fair'), ('D', 'Grade D - Poor'), ('BER', 'Beyond Economic Repair'), ('UNGRADED', 'Not yet graded')], default='UNGRADED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='donors.donor')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='locations.location')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='workflow.stage')),
                ('device_specification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='devices.devicespecification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
