# Generated by Django 5.0.2 on 2026-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='parts_cost_pounds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='device',
            name='parts_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='parts_status',
            field=models.CharField(choices=[('NOT_NEEDED', 'No parts required'), ('REQUESTED', 'Part requested'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('FITTED', 'Fitted')], default='NOT_NEEDED', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='wipe_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='wipe_status',
            field=models.CharField(choices=[('DONOR_WIPED', 'Donor confirmed pre-wiped'), ('NO_STORAGE', 'No storage media present'), ('PENDING', 'Needs wiping'), ('PASS', 'Wipe completed successfully'), ('FAIL', 'Wipe attempted but failed')], default='PENDING', max_length=20),
        ),
    ]
