# Generated by Django 5.0.2 on 2026-05-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_parts_cost_pounds_device_parts_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='memory_gb_upgraded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='processor_upgraded',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='storage_size_gb_upgraded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicespecification',
            name='memory_gb_upgraded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicespecification',
            name='processor_upgraded',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devicespecification',
            name='storage_size_gb_upgraded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
