# Generated by Django 5.0.2 on 2026-05-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_memory_gb_upgraded_device_processor_upgraded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicespecification',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
