# Generated by Django 5.0.2 on 2026-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_serial_unique_from_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicespecification',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
