# Generated by Django 5.0.2 on 2026-05-22 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicespecification_serial_number'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='donation_pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='donations.donationpledge'),
        ),
    ]
