# Generated by Django 5.0.2 on 2026-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_donation_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='allocation_intent',
            field=models.CharField(choices=[('UNDECIDED', 'Undecided'), ('SALE', 'Sale'), ('DEVICE_BANK', 'Device Bank'), ('RECYCLING', 'Recycling'), ('OTHER', 'Other')], default='UNDECIDED', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='market_value_pounds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual estimated market value (£)', max_digits=8, null=True),
        ),
    ]
