# Generated by Django 5.0.2 on 2026-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_allocation_intent_device_market_value_pounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipient_type', models.CharField(choices=[('BUSINESS', 'Business'), ('CHARITY', 'Charity'), ('SCHOOL', 'School'), ('INDIVIDUAL', 'Individual'), ('INTERNAL', 'Internal')], max_length=20)),
                ('erpnext_customer_id', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
