# Generated by Django 5.0.2 on 2026-05-26 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_order_id', models.CharField(max_length=50, unique=True)),
                ('erpnext_order_url', models.URLField(blank=True)),
                ('summary', models.CharField(help_text="e.g. '50 Laptops Grade A for Acme Corp'", max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('COLLECTION', 'Collection'), ('DELIVERY', 'Delivery')], default='COLLECTION', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — awaiting allocation'), ('IN_PROGRESS', 'In Progress — devices being allocated'), ('READY', 'Ready — all devices picked and awaiting dispatch'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20)),
                ('allocation_type', models.CharField(choices=[('SALE', 'Sale'), ('LEASE', 'Lease'), ('CHARITY_DONATION', 'Charity Donation'), ('RECYCLING', 'Recycling'), ('RAAS_RETURN', 'RaaS Return'), ('INTERNAL_USE', 'Internal Use'), ('TRAINING', 'Training')], max_length=20)),
                ('erpnext_reference', models.CharField(blank=True, help_text='Sales Order ID or other ERPNext reference', max_length=100)),
                ('grant_reference', models.CharField(blank=True, help_text='ERPNext grant/funding reference (if grant-funded)', max_length=50)),
                ('price_pounds', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='devices.device')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.recipient')),
                ('fulfilment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.fulfilmentrequest')),
            ],
        ),
    ]
