# Generated by Django 5.0.2 on 2026-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_fulfilmentrequest_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='win11_compatible',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
    ]
