# Generated by Django 5.0.2 on 2026-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_win11_compatible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='parts_status',
            field=models.CharField(choices=[('UNKNOWN', 'Not known'), ('NOT_NEEDED', 'No parts required'), ('REQUESTED', 'Part requested'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('FITTED', 'Fitted')], default='UNKNOWN', max_length=20),
        ),
    ]
