# Generated by Django 5.0.2 on 2026-06-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_parts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prefix', models.CharField(max_length=4)),
                ('current_number', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_prefix'],
                'unique_together': {('date_prefix',)},
            },
        ),
    ]
