# Generated by Django 5.0.2 on 2026-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_inventorysequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='erpnext_dn_reference',
            field=models.CharField(blank=True, help_text='ERPNext Delivery Note name (e.g. DN-001) — for reconciliation', max_length=50),
        ),
        migrations.AddField(
            model_name='fulfilmentrequest',
            name='requested_spec',
            field=models.JSONField(blank=True, default=dict, help_text="Structured spec criteria promised to the customer. e.g. {'type': 'LAPTOP', 'grade': 'A', 'min_memory_gb': 8}"),
        ),
    ]
