# Generated by Django 5.0.2 on 2026-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_allocation_erpnext_dn_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='allocation_intent',
            field=models.CharField(choices=[('UNDECIDED', 'Undecided'), ('SALE', 'Sale'), ('DEVICE_BANK', 'Device Bank'), ('RECYCLING', 'Recycling'), ('RESERVED', 'Reserved'), ('OTHER', 'Other')], default='UNDECIDED', max_length=20),
        ),
    ]
