# Generated by Django 5.0.2 on 2026-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_alter_device_allocation_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reserved_for_name',
            field=models.CharField(blank=True, help_text='Organisation/person this device is reserved for', max_length=200),
        ),
    ]
