# Generated by Django 5.0.2 on 2026-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='target_ready_by',
            field=models.DateField(blank=True, help_text='Target date for devices to be ready for dispatch', null=True),
        ),
    ]
