# Generated by Django 5.0.2 on 2026-06-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_allocation_target_ready_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilmentrequest',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Number of devices requested'),
        ),
    ]
