# Generated by Django 5.0.2 on 2026-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_fulfilmentrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilmentrequest',
            name='item_code',
            field=models.CharField(blank=True, help_text='ERPNext item code e.g. LAPTOP-STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='fulfilmentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending — awaiting allocation'), ('IN_PROGRESS', 'In Progress — devices being allocated'), ('READY', 'Ready — all devices picked and awaiting dispatch'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold - no matching devices available')], default='PENDING'),
        ),
    ]
