# Generated by Django 5.0.2 on 2026-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_add_item_code_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='audit_status',
            field=models.CharField(choices=[('PENDING', 'Audit pending'), ('PASS', 'Audit passed'), ('FAIL', 'Audit failed')], default='PENDING', max_length=20),
        ),
    ]
