# Generated by Django 5.0.2 on 2026-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_device_audit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('DISPATCHED', 'Dispatched'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20),
        ),
    ]
