# Generated by Django 5.0.2 on 2026-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_alter_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='erpnext_stock_entry',
            field=models.CharField(blank=True, help_text='ERPNext Stock Entry name (e.g. MAT-STE-2026-00001). Null = not yet pushed.', max_length=100, null=True),
        ),
    ]
