# Generated by Django 5.0.2 on 2026-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_device_erpnext_stock_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='audit_status',
        ),
        migrations.RemoveField(
            model_name='device',
            name='grade',
        ),
        migrations.AddField(
            model_name='device',
            name='final_audit_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not yet audited'), ('PASS', 'Audit passed'), ('FAIL', 'Audit failed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='final_grade',
            field=models.CharField(choices=[('A', 'Grade A - Excellent'), ('B', 'Grade B - Good'), ('C', 'Grade C - Fair'), ('D', 'Grade D - Poor'), ('BER', 'Beyond Economic Repair'), ('UNGRADED', 'Not yet graded')], default='UNGRADED', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='initial_audit_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not yet audited'), ('PASS', 'Audit passed'), ('FAIL', 'Audit failed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='initial_grade',
            field=models.CharField(choices=[('A', 'Grade A - Excellent'), ('B', 'Grade B - Good'), ('C', 'Grade C - Fair'), ('D', 'Grade D - Poor'), ('BER', 'Beyond Economic Repair'), ('UNGRADED', 'Not yet graded')], default='UNGRADED', max_length=20),
        ),
    ]
