# Generated by Django 5.0.2 on 2026-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_remove_device_audit_status_remove_device_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='allocation_intent',
            field=models.CharField(choices=[('UNDECIDED', 'Undecided'), ('FOR_SALE', 'For Sale'), ('DEVICE_BANK', 'Device Bank'), ('PARTS_HARVESTING', 'Parts Harvesting'), ('RECYCLE', 'Recycle')], default='UNDECIDED', max_length=20),
        ),
    ]
