# Generated by Django 5.0.2 on 2026-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_device_allocation_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.CharField(choices=[('NONE', 'None'), ('WINDOWS_11', 'Windows 11'), ('LINUX_UBUNTU', 'Linux - Ubuntu'), ('LINUX_MINT', 'Linux - Mint'), ('LINUX_OTHER', 'Linux - Other'), ('OTHER_OS', 'Other OS')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='qa_status',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='refurb_notes',
            field=models.TextField(blank=True),
        ),
    ]
