# Generated by Django 5.0.2 on 2026-08-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_alter_device_allocation_intent_repairtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicespecification',
            name='drive_serial',
            field=models.CharField(blank=True, default='', help_text='Drive serial(s) from FOG hdserial. Multi-drive: comma-separated string.', max_length=500),
        ),
    ]
