# Generated by Django 5.0.2 on 2026-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_devicespecification_drive_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicespecification',
            name='hdmodel_raw',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devicespecification',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
