# Generated by Django 5.0.2 on 2026-08-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_devicespecification_hdmodel_raw_and_more'),
        ('wipe', '0003_auditrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='final_audit',
            field=models.ForeignKey(blank=True, help_text='Cedar audit certificate designated as final (QA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_final_audit', to='wipe.auditrecord'),
        ),
        migrations.AddField(
            model_name='device',
            name='initial_audit',
            field=models.ForeignKey(blank=True, help_text='Cedar audit certificate designated as initial (check-in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_initial_audit', to='wipe.auditrecord'),
        ),
    ]
