# Generated by Django 5.0.2 on 2026-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_device_final_audit_device_initial_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('ALL_IN_ONE', 'All-in-One'), ('TABLET', 'Tablet'), ('MONITOR', 'Monitor'), ('SERVER', 'Server'), ('OTHER', 'Other')], default='LAPTOP', max_length=20),
        ),
    ]
