# Generated by Django 5.0.2 on 2026-08-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_alter_device_device_type'),
        ('wipe', '0004_auditrecord_cedar_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latest_audit',
            field=models.ForeignKey(blank=True, help_text='Most recent Cedar asset audit for this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wipe.auditrecord'),
        ),
    ]
