# Generated by Django 5.0.2 on 2026-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_device_latest_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicespecification',
            name='storage_type_upgraded',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVME', 'NVMe'), ('EMMC', 'eMMC'), ('UNKNOWN', 'Unknown')], max_length=20, null=True),
        ),
    ]
