# Generated by Django 5.0.2 on 2026-08-25 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_devicespecification_storage_type_upgraded'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(choices=[('defects', 'Open refurb defects'), ('final_audit', 'Final Cedar audit')], max_length=50)),
                ('justification', models.TextField()),
                ('overridden_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_overrides', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gateoverride',
            constraint=models.UniqueConstraint(fields=('device', 'gate'), name='unique_gate_override_per_device'),
        ),
    ]
