# Generated by Django 5.0.2 on 2026-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_gateoverride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pat_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='pat_pass_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='pat_status',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('N/A', 'N/A')], max_length=4, null=True),
        ),
    ]
