# Generated by Django 5.0.2 on 2026-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0034_device_pat_justification_device_pat_pass_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='checklist_warning',
            field=models.BooleanField(default=False, help_text='True when a stage was exited without its checklist completed'),
        ),
        migrations.AddField(
            model_name='device',
            name='checklist_warning_stage',
            field=models.CharField(blank=True, help_text='Stage code whose checklist was skipped (e.g. CHECK_IN)', max_length=50, null=True),
        ),
    ]
