# Generated by Django 5.0.2 on 2026-10-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_device_checklist_warning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='erasure_exception_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='erasure_exception_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='erasure_exception_category',
            field=models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Not required'), ('NOT_POSSIBLE', 'Not possible via Cedar'), ('WIPED_EXTERNAL', 'Wiped outside Cedar')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='erasure_exception_note',
            field=models.TextField(blank=True, default='', help_text='Mandatory when reason is OTHER'),
        ),
        migrations.AddField(
            model_name='device',
            name='erasure_exception_reason',
            field=models.CharField(blank=True, choices=[('DONOR_PRE_WIPED', 'Donor confirmed pre-wiped'), ('NO_STORAGE_MEDIA', 'No storage media present'), ('SOLDERED_NAND', 'Soldered storage (e.g. Apple NAND)'), ('UNSUPPORTED_CONTROLLER', 'Controller not supported by Cedar'), ('DRIVE_DAMAGED', 'Drive damaged / unreadable'), ('REMOVED_WIPED_ELSEWHERE', 'Drive removed and wiped elsewhere'), ('THIRD_PARTY_PRODUCT', 'Wiped with third-party product'), ('LINUX_CLI', 'Wiped via Linux CLI'), ('OTHER', 'Other (note required)')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='device',
            name='erasure_required',
            field=models.BooleanField(default=True, help_text='False only when a categorised exception has been granted'),
        ),
        migrations.AlterField(
            model_name='device',
            name='wipe_status',
            field=models.CharField(choices=[('DONOR_WIPED', 'Donor confirmed pre-wiped'), ('NO_STORAGE', 'No storage media present'), ('PENDING', 'Needs wiping'), ('PASS', 'Wipe completed successfully'), ('FAIL', 'Wipe attempted but failed'), ('N/A', 'Not applicable — wiping not required'), ('WIPED_EXTERNAL', 'Wiped outside Cedar (manual/third-party)')], default='PENDING', max_length=20),
        ),
    ]
