# Generated by Django 5.0.2 on 2026-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_device_erasure_exception_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='erasure_exception_reason',
            field=models.CharField(blank=True, choices=[('DONOR_DECLARED', 'Declared by donor on donation pledge'), ('DONOR_PRE_WIPED', 'Donor confirmed pre-wiped (operator-recorded)'), ('NO_STORAGE_MEDIA', 'No storage media present'), ('SOLDERED_NAND', 'Soldered storage (e.g. Apple NAND)'), ('UNSUPPORTED_CONTROLLER', 'Controller not supported by Cedar'), ('DRIVE_DAMAGED', 'Drive damaged / unreadable'), ('REMOVED_WIPED_ELSEWHERE', 'Drive removed and wiped elsewhere'), ('THIRD_PARTY_PRODUCT', 'Wiped with third-party product'), ('LINUX_CLI', 'Wiped via Linux CLI'), ('OTHER', 'Other (note required)')], default='', max_length=30),
        ),
    ]
