# Generated by Django 5.0.2 on 2026-10-05 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_erasure_reason_donor_declared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WipeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('CERTIFICATE', 'Certificate (wiped by another tool)'), ('DESTRUCTION_PHOTO', 'Destruction photograph'), ('CEDAR_FAILURE_REPORT', 'Failed Cedar report (anchor)')], max_length=30)),
                ('file', models.FileField(upload_to='wipe_evidence/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipe_evidence', to='devices.device')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'wipe evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
