# Generated by Django 5.0.2 on 2026-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_wipeevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='erasure_exception_reason',
            field=models.CharField(blank=True, choices=[('DONOR_DECLARED', 'Declared by donor on donation pledge'), ('NO_STORAGE_MEDIA', 'No storage media present'), ('REMOVED_WIPED_ELSEWHERE', 'Drive removed and wiped elsewhere'), ('OTHER', 'Other (note required)')], default='', max_length=30),
        ),
    ]
