# Generated by Django 5.0.2 on 2026-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0039_erasure_reason_simplify'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='drive_removed',
            field=models.BooleanField(default=False, help_text='True when the storage medium has been physically removed'),
        ),
    ]
