# Generated by Django 5.0.2 on 2026-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0040_device_drive_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateoverride',
            name='gate',
            field=models.CharField(choices=[('defects', 'Open refurb defects'), ('final_audit', 'Final Cedar audit'), ('erasure', 'Unresolved erasure obligation')], max_length=50),
        ),
    ]
