# Generated by Django 5.0.2 on 2026-10-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_alter_gateoverride_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicespecification',
            name='gpu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
