# Generated by Django 5.0.2 on 2026-05-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_migrate_to_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
