# Generated by Django 5.0.2 on 2026-05-20 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0005_alter_devicespecification_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_contact', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_erpnext_id', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(choices=[('WEBFORM', 'Webform'), ('STAFF', 'Staff Entry'), ('CSV_IMPORT', 'CSV Import')], default='STAFF', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transfer_of_title_signed', models.BooleanField(default=False)),
                ('transfer_of_title_signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('device_list_file', models.FileField(blank=True, help_text='CSV file with make, model, serial_number, device_type', null=True, upload_to='donation_csv/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('SERVER', 'Server'), ('TABLET', 'Tablet'), ('SMARTPHONE', 'Smartphone'), ('MONITOR', 'Monitor'), ('NETWORK', 'Network Equipment'), ('OTHER', 'Other')], default='LAPTOP', max_length=20)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('RECEIVED', 'Received'), ('MISSING', 'Missing'), ('UNEXPECTED', 'Unexpected')], default='EXPECTED', max_length=20)),
                ('interim_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_devices', to='donations.donationpledge')),
                ('matched_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_device_records', to='devices.device')),
            ],
            options={
                'ordering': ['donation_pledge', 'serial_number'],
            },
        ),
    ]
