# Generated by Django 5.0.2 on 2026-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_expecteddevice_storage_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expecteddevice',
            name='storage_removed',
        ),
        migrations.AddField(
            model_name='donationpledge',
            name='storage_removed',
            field=models.BooleanField(default=False, help_text='Donor confirmed storage has been removed or devices already wiped'),
        ),
    ]
