# Generated by Django 5.0.2 on 2026-06-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_expecteddevice_storage_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpledge',
            name='donor_mobile',
            field=models.CharField(blank=True, help_text='Phone number for WhatsApp notifications', max_length=30),
        ),
    ]
