# Generated by Django 5.0.2 on 2026-08-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationpledge_donor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expecteddevice',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
