# Generated by Django 5.0.2 on 2026-05-08 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organisation name', max_length=200)),
                ('dolibarr_id', models.IntegerField(blank=True, help_text='Reference to Dolibarr third party', null=True)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact', max_length=100)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('default_ownership_type', models.CharField(choices=[('DONATION', 'Ownership transfers to ReCognition'), ('RAAS', 'Refurb-as-a-Service where ownership stays with donor'), ('LEASE_ASSET', 'ReCognition-owned asset for leasing'), ('INTERNAL', 'Internal use device')], default='DONATION', help_text='Default for devices from this donor', max_length=20)),
                ('requires_wipe_certificate', models.BooleanField(default=True, help_text='Send wipe cert automatically')),
                ('requires_environmental_report', models.BooleanField(default=False, help_text='Send impact report')),
            ],
        ),
    ]
